package commands

import (
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/darttroll/gemini-router/internal/config"
)

func TestSetupCommand_CreateDirectories(t *testing.T) {
	dir := t.TempDir()
	dataDir := filepath.Join(dir, "data")

	cfg := &config.Config{
		AgyPath: "/usr/bin/agy",
		DataDir: dataDir,
		Workers: []config.WorkerConfig{
			{Username: "alice", Enabled: true},
		},
	}

	cmd := NewSetupCommand(cfg)
	// Exercise directory creation without installing sudoers.
	if err := cmd.CreateDirectories(); err != nil {
		t.Fatalf("CreateDirectories() error: %v", err)
	}

	// Verify the directories were created.
	if _, err := os.Stat(dataDir); err != nil {
		t.Errorf("dataDir not created: %v", err)
	}

	logsDir := filepath.Join(dataDir, "logs")
	if _, err := os.Stat(logsDir); err != nil {
		t.Errorf("logsDir not created: %v", err)
	}
}

func TestSetupCommand_GenerateSudoers(t *testing.T) {
	cfg := &config.Config{
		AgyPath: "/opt/agy/bin/agy",
		Workers: []config.WorkerConfig{
			{Username: "alice", Enabled: true},
			{Username: "bob", Enabled: false},
			{Username: "charlie", Enabled: true},
		},
	}

	cmd := NewSetupCommand(cfg)
	content := cmd.GenerateSudoersContent()

	expected := "# /etc/sudoers.d/gemini-router\n# Generated by: gemini-router setup\nroot ALL=(alice) NOPASSWD: /opt/agy/bin/agy\nroot ALL=(charlie) NOPASSWD: /opt/agy/bin/agy\n"
	if content != expected {
		t.Errorf("expected %q, got %q", expected, content)
	}
}

func TestSetupCommand_InitDatabase(t *testing.T) {
	dir := t.TempDir()
	dataDir := filepath.Join(dir, "data")

	cfg := &config.Config{
		DataDir: dataDir,
	}

	cmd := NewSetupCommand(cfg)
	if err := os.MkdirAll(dataDir, 0755); err != nil {
		t.Fatal(err)
	}

	if err := cmd.InitDatabase(); err != nil {
		t.Fatalf("InitDatabase() error: %v", err)
	}

	dbPath := filepath.Join(dataDir, "gemini-router.db")
	if _, err := os.Stat(dbPath); err != nil {
		t.Errorf("database file not created: %v", err)
	}
}

func TestSetupCommandGenerateSudoersUsesWorkerSpecificAgyPath(t *testing.T) {
	cfg := &config.Config{AgyPath: "/global/agy", Workers: []config.WorkerConfig{{Username: "alice", Enabled: true, AgyPath: "/home/alice/bin/agy"}}}
	got := NewSetupCommand(cfg).GenerateSudoersContent()
	if !strings.Contains(got, "root ALL=(alice) NOPASSWD: /home/alice/bin/agy") {
		t.Fatalf("sudoers=%q", got)
	}
}

func TestSetupCommandCreateDirectoriesHardensExistingModes(t *testing.T) {
	dataDir := filepath.Join(t.TempDir(), "data")
	logsDir := filepath.Join(dataDir, "logs")
	if err := os.MkdirAll(logsDir, 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.Chmod(dataDir, 0755); err != nil {
		t.Fatal(err)
	}
	if err := os.Chmod(logsDir, 0755); err != nil {
		t.Fatal(err)
	}
	cmd := NewSetupCommand(&config.Config{DataDir: dataDir})
	if err := cmd.CreateDirectories(); err != nil {
		t.Fatal(err)
	}
	for _, path := range []string{dataDir, logsDir} {
		info, err := os.Stat(path)
		if err != nil {
			t.Fatal(err)
		}
		if got := info.Mode().Perm(); got != 0700 {
			t.Fatalf("%s mode=%o want 700", path, got)
		}
	}
}

func TestWriteSudoersValidationFailurePreservesExistingFile(t *testing.T) {
	dir := t.TempDir()
	target := filepath.Join(dir, "gemini-router")
	if err := os.WriteFile(target, []byte("old-policy\n"), 0440); err != nil {
		t.Fatal(err)
	}
	validator := filepath.Join(dir, "visudo-fail")
	if err := os.WriteFile(validator, []byte("#!/bin/sh\necho invalid >&2\nexit 1\n"), 0755); err != nil {
		t.Fatal(err)
	}
	cmd := NewSetupCommand(&config.Config{AgyPath: "/usr/bin/agy", Workers: []config.WorkerConfig{{Username: "alice", Enabled: true}}})
	cmd.sudoersDir = dir
	cmd.visudoPath = validator
	if err := cmd.WriteSudoers(); err == nil {
		t.Fatal("expected visudo validation failure")
	}
	data, err := os.ReadFile(target)
	if err != nil {
		t.Fatal(err)
	}
	if string(data) != "old-policy\n" {
		t.Fatalf("existing sudoers changed: %q", data)
	}
}
