package commands

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/darttroll/gemini-router/internal/config"
	"github.com/darttroll/gemini-router/internal/proc"
	"github.com/darttroll/gemini-router/internal/storage"
)

// SetupCommand implements the setup subcommand.
type SetupCommand struct {
	cfg        *config.Config
	sudoersDir string
	visudoPath string
}

// NewSetupCommand creates a SetupCommand.
func NewSetupCommand(cfg *config.Config) *SetupCommand {
	return &SetupCommand{cfg: cfg, sudoersDir: "/etc/sudoers.d", visudoPath: "visudo"}
}

// Run initializes private directories, the database, and sudoers.
func (s *SetupCommand) Run() error {
	fmt.Println("gemini-router setup:")

	// 1. Create runtime directories.
	fmt.Print("  Creating directories... ")
	if err := s.CreateDirectories(); err != nil {
		fmt.Println("FAIL")
		return fmt.Errorf("creating directories: %w", err)
	}
	fmt.Println("OK")

	// 2. Initialize the database.
	fmt.Print("  Initializing database... ")
	if err := s.InitDatabase(); err != nil {
		fmt.Println("FAIL")
		return fmt.Errorf("initializing database: %w", err)
	}
	fmt.Println("OK")

	// 3. Validate and install sudoers.
	fmt.Print("  Generating sudoers... ")
	if err := s.WriteSudoers(); err != nil {
		fmt.Printf("FAIL (%v)\n", err)
		return fmt.Errorf("installing sudoers: %w", err)
	}
	fmt.Println("OK")

	fmt.Println("Setup complete!")
	return nil
}

// CreateDirectories creates data_dir and its log directory.
func (s *SetupCommand) CreateDirectories() error {
	dirs := []string{
		s.cfg.DataDir,
		filepath.Join(s.cfg.DataDir, "logs"),
	}
	for _, d := range dirs {
		if err := os.MkdirAll(d, 0700); err != nil {
			return fmt.Errorf("creating %s: %w", d, err)
		}
		if err := os.Chmod(d, 0700); err != nil {
			return fmt.Errorf("securing %s: %w", d, err)
		}
	}
	return nil
}

// InitDatabase initializes the SQLite database.
func (s *SetupCommand) InitDatabase() error {
	dbPath := filepath.Join(s.cfg.DataDir, "gemini-router.db")
	store, err := storage.New(dbPath)
	if err != nil {
		return err
	}
	if err := store.Close(); err != nil {
		return err
	}
	return os.Chmod(dbPath, 0600)
}

// GenerateSudoersContent renders the sudoers policy.
func (s *SetupCommand) GenerateSudoersContent() string {
	var sb strings.Builder
	sb.WriteString("# /etc/sudoers.d/gemini-router\n")
	sb.WriteString("# Generated by: gemini-router setup\n")
	for _, w := range s.cfg.Workers {
		if !w.Enabled {
			continue
		}
		sb.WriteString(fmt.Sprintf("root ALL=(%s) NOPASSWD: %s\n", w.Username, s.cfg.GetAgyPath(w.Username)))
	}
	return sb.String()
}

// WriteSudoers validates and atomically installs the sudoers policy.
func (s *SetupCommand) WriteSudoers() error {
	content := s.GenerateSudoersContent()
	if content == "" {
		return fmt.Errorf("no enabled workers")
	}
	dir := s.sudoersDir
	tmp, err := os.CreateTemp(dir, ".gemini-router-*")
	if err != nil {
		return err
	}
	tmpPath := tmp.Name()
	defer os.Remove(tmpPath)
	if err := tmp.Chmod(0440); err != nil {
		tmp.Close()
		return err
	}
	if _, err := tmp.WriteString(content); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	ctx, cancel := context.WithTimeout(context.Background(), 10*time.Second)
	defer cancel()
	result, err := proc.Run(ctx, nil, s.visudoPath, "-cf", tmpPath)
	if err != nil {
		return fmt.Errorf("visudo validation failed: %w: %s", err, strings.TrimSpace(string(result.CombinedOutput())))
	}
	return os.Rename(tmpPath, filepath.Join(dir, "gemini-router"))
}
